##TASK 1

In [1]:
import pandas as pd

In [2]:
import plotly.express as px

In [3]:
from datetime import datetime

In [4]:
import pytz

In [5]:
df = pd.read_csv(r"C:\Users\NAYNALAXANE\Downloads\play store data.csv")

In [6]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [7]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [8]:
sentiment_df = pd.read_csv(r"C:\Users\NAYNALAXANE\Downloads\User Reviews.csv",
encoding='latin1',
engine='python',
on_bad_lines='skip'
)
sentiment_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [9]:
merged_df = pd.merge(df, sentiment_df[['App', 'Sentiment_Subjectivity']], on='App', how='left')
merged_df[['App', 'Sentiment_Subjectivity']].head()

                                              App  Sentiment_Subjectivity
0  Photo Editor & Candy Camera & Grid & ScrapBook                     NaN
1                             Coloring book moana                1.000000
2                             Coloring book moana                0.833333
3                             Coloring book moana                0.000000
4                             Coloring book moana                     NaN

In [10]:
merged_df['Reviews'] = pd.to_numeric(merged_df['Reviews'], errors='coerce')

merged_df['Installs'] = merged_df['Installs'].astype(str)
merged_df['Installs'] = merged_df['Installs'].str.replace(',', '', regex=False)
merged_df['Installs'] = merged_df['Installs'].str.replace('+', '', regex=False)
merged_df['Installs'] = pd.to_numeric(merged_df['Installs'], errors='coerce')

merged_df = merged_df[merged_df['Size'].str.contains('M', na=False)]

merged_df['Size'] = merged_df['Size'].str.replace('M', '', regex=False)
merged_df['Size'] = pd.to_numeric(merged_df['Size'], errors='coerce')

merged_df[['Reviews','Installs','Size']].head()

   Reviews  Installs  Size
0    159.0   10000.0  19.0
1    967.0  500000.0  14.0
2    967.0  500000.0  14.0
3    967.0  500000.0  14.0
4    967.0  500000.0  14.0

In [11]:
categories = [
    'GAME','BEAUTY','BUSINESS','COMICS',
    'COMMUNICATION','DATING',
    'ENTERTAINMENT','SOCIAL','EVENTS'
]

task1_df = merged_df[
    (merged_df['Rating'] > 3.5) &
    (merged_df['Category'].isin(categories)) &
    (merged_df['Reviews'] > 500) &
    (~merged_df['App'].str.contains('S', case=False, na=False)) &
    (merged_df['Sentiment_Subjectivity'] > 0.5) &
    (merged_df['Installs'] > 50000)
]

task1_df[['App','Category','Rating','Reviews',
          'Installs','Sentiment_Subjectivity']].head()

,App,Category,Rating,Reviews,Installs,Sentiment_Subjectivity
2934,Google Primer,BUSINESS,4.4,62272.0,10000000.0,0.750000
2936,Google Primer,BUSINESS,4.4,62272.0,10000000.0,0.600000
3106,Call Blocker,BUSINESS,4.6,188841.0,5000000.0,0.881250
3153,Call Blocker,BUSINESS,4.6,188841.0,5000000.0,0.559286
3175,Call Blocker,BUSINESS,4.6,188841.0,5000000.0,0.525758

In [12]:
from datetime import datetime
import pytz

ist = pytz.timezone('Asia/Kolkata')
current_time = datetime.now(ist)

task1_df['Category_translated'] = task1_df['Category'].replace({
    'BEAUTY': 'सौंदर्य',       # Hindi
    'BUSINESS': 'வணிகம்',      # Tamil
    'DATING': 'Dating'         # German next step
})

task1_df['Category_translated'] = task1_df['Category_translated'].replace({
    'DATING': 'Partnersuche'   # German
})

if 16 <= current_time.hour < 19:
    print("Inside allowed time")
else:
    print("Chart available only between 4 PM and 7 PM IST")

Chart available only between 4 PM and 7 PM IST

C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3321711722.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task1_df['Category_translated'] = task1_df['Category'].replace({
C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3321711722.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task1_df['Category_translated'] = task1_df['Category_translated'].replace({

In [13]:
import pandas as pd
import plotly.express as px
from datetime import datetime
import pytz

# Merge datasets
merged_df = pd.merge(
    df,
    sentiment_df[['App','Sentiment_Subjectivity']],
    on='App',
    how='left'
)

# Clean Reviews
merged_df['Reviews'] = pd.to_numeric(
    merged_df['Reviews'],
    errors='coerce'
)

# Clean Installs
merged_df['Installs'] = (
    merged_df['Installs']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('+', '', regex=False)
)

merged_df['Installs'] = pd.to_numeric(
    merged_df['Installs'],
    errors='coerce'
)

# Clean Size (MB only)

merged_df['Size'] = merged_df['Size'].astype(str)
merged_df = merged_df[merged_df['Size'].str.contains('M',na=False)]
merged_df['Size'] = merged_df['Size'].str.replace('M', '',regex=False)
merged_df['Size'] = pd.to_numeric(merged_df['Size'],errors='coerce')
          



# Required categories
categories = [
    'GAME',
    'BEAUTY',
    'BUSINESS',
    'COMICS',
    'COMMUNICATION',
    'DATING',
    'ENTERTAINMENT',
    'SOCIAL',
    'EVENTS'
]

# Apply filters
task1_df = merged_df[
    (merged_df['Rating'] > 3.5) &
    (merged_df['Category'].isin(categories)) &
    (merged_df['Reviews'] > 500) &
    (~merged_df['App'].str.contains('S', case=False, na=False)) &
    (merged_df['Sentiment_Subjectivity'] > 0.5) &
    (merged_df['Installs'] > 50000)
].copy()

# Translation
task1_df['Category_translated'] = task1_df['Category'].replace({
    'BEAUTY':'सौंदर्य',
    'BUSINESS':'வணிகம்',
    'DATING':'Partnersuche'
})

# Time condition
ist = pytz.timezone('Asia/Kolkata')
current_time = datetime.now(ist)

if 17 <= current_time.hour < 19:

    fig = px.scatter(
        task1_df,
        x='Size',
        y='Rating',
        size='Installs',
        color='Category_translated',
        hover_name='App',
        title='Bubble Chart: Size vs Rating'
    )

    # GAME only pink
    fig.for_each_trace(
        lambda t: t.update(marker_color='pink')
        if t.name == 'GAME'
        else ()
    )

    fig.show()

else:
    print("Chart available only between 5 PM and 7 PM IST")

Chart available only between 5 PM and 7 PM IST

In [14]:
import plotly.io as pio
pio.renderers.default = 'browser'

In [15]:
task1_df['Category'].value_counts()

Category
GAME             3251
DATING            357
ENTERTAINMENT     163
SOCIAL             53
COMMUNICATION       6
BUSINESS            5
Name: count, dtype: int64

In [16]:
task1_df[task1_df['Category'] == 'BEAUTY'].head()
task1_df[task1_df['Category'] == 'BEAUTY'].shape

(0, 15)

## TASK 2

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv(r"C:\Users\NAYNALAXANE\Downloads\play store data.csv")

In [19]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [20]:
df['Installs'] = df['Installs'].astype(str).str.replace(',', '')
df['Installs'] = df['Installs'].str.replace('+', '')
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

In [21]:
filtered_map = df[~df['Category'].str.startswith(('A','C','G','S'), na=False)]

In [22]:
category_installs = filtered_map.groupby('Category')['Installs'].sum().reset_index()

In [23]:
top5 = category_installs.nlargest(5, 'Installs')

In [24]:
top5

              Category      Installs
21        PRODUCTIVITY  1.417609e+10
22               TOOLS  1.145277e+10
8               FAMILY  1.025826e+10
20         PHOTOGRAPHY  1.008825e+10
17  NEWS_AND_MAGAZINES  7.496318e+09

In [25]:
top5['Highlight'] = top5['Installs'] > 1000000

In [26]:
top5

              Category      Installs  Highlight
21        PRODUCTIVITY  1.417609e+10       True
22               TOOLS  1.145277e+10       True
8               FAMILY  1.025826e+10       True
20         PHOTOGRAPHY  1.008825e+10       True
17  NEWS_AND_MAGAZINES  7.496318e+09       True

In [27]:
import plotly.express as px
import plotly.io as pio
from datetime import datetime
import pytz

pio.renderers.default = 'browser'


top5['Country'] = [
    'India',
    'United States',
    'Germany',
    'Brazil',
    'Canada'
]

# Highlight installs > 1 million
top5['Highlight'] = top5['Installs'] > 1000000

ist = pytz.timezone('Asia/Kolkata')
current_hour = datetime.now(ist).hour

if 18 <= current_hour < 20:

    fig = px.choropleth(
        top5,
        locations='Country',
        locationmode='country names',
        color='Highlight',
        hover_name='Category',
        hover_data=['Installs'],
        title='Global Installs by Top 5 Categories'
    )

    fig.show()

else:
    print("Choropleth map available only between 6 PM and 8 PM IST")

Choropleth map available only between 6 PM and 8 PM IST

## TASK 3

In [28]:
import os
os.listdir(r"C:\Users\NAYNALAXANE\Downloads")

['01-08-2025Attendence Report -01-08-2025-11_37_04 AM.pdf',
 '1. (1).jpg',
 '1..jpg',
 '1.jpg',
 '10th_Marksheet.jpg',
 '10th_Marksheet.pdf',
 '2..jpg',
 '2.jpg',
 '3..jpg',
 '3.jpg',
 '3of9_barcode (1).zip',
 '3of9_barcode.zip',
 '4..jpg',
 '4.jpg',
 '5..jpg',
 '5.jpg',
 '5070a02f8bc5c92adownload.zip',
 '6.jpg',
 '6th sem marsksheet.jpg',
 'A.P.10th.pdf',
 'Aadhaar.jpeg',
 'acknowledgementSlip_S1334980604000.pdf',
 'acknowledgementSlip_S1357370039050.pdf',
 'admit_card_IITM-AI-DS-000000.png',
 'Agile Methodology.docx',
 'Air Insights - Lovable.html',
 'Air Insights - Lovable_files',
 'apollo certifate.pdf',
 'archive (1).zip',
 'archive (2).zip',
 'archive (3).zip',
 'archive (4)',
 'archive (4).zip',
 'archive (5).zip',
 'archive (6).zip',
 'archive (7).zip',
 'archive (8).zip',
 'archive.zip',
 'Automobile Institution List.xlsx',
 'B.jpg',
 'B.pdf',
 'B1.pdf',
 'base.apk',
 'BR Research-1.docx',
 'BR Research-1.pdf',
 'BSc_Major Project_Synopsis.docx',
 'BSc_Major Project_Synopsis.pdf',
 'candidate Recruitmnet Tracker(EQ sheet) (1).xlsx',
 'candidate Recruitmnet Tracker(EQ sheet).xlsx',
 'caste certificate nayna.jpg',
 'caste nayna.jpg',
 'CBT Result JE (HR) Advt. No. 01-2025-CHQ.pdf',
 'Chitralekha Tukaram Muneshwar CV.pdf',
 'Conditional latter shruti khillare',
 'Conditional Letter - Sandhya Tirthraj Bharti.pdf',
 'Copy of Copy of Webinar_intersted_candidates__(1)(1)(1).xlsx',
 'Copy of Webinar intersted candidates(1).xlsx',
 'Copy of Webinar_intersted_candidates__(1)(1).xlsx',
 'CV Nayna Laxane.docx',
 'CV Nayna Laxane.pdf',
 'CV Nayna Laxane.ppt',
 'Daywise Attendance_Off-Role_2025 - July_2025.xlsx',
 'Daywise Attendance_Off-Role_2025 - June_2025 (1).xlsx',
 'Daywise Attendance_On-Role Employees_2025 - July_2025.xlsx',
 'Daywise Attendance_TDS_2025 - July_2025.xlsx',
 'dd5870495748fc2f0dcf658e9ea90e93f6a2858f9f2ceb70aee8dc7f3dd4f495_encrypt_signedFinal.pdf',
 'Declaration.jpg',
 'desktop.ini',
 'disha cer.jpg',
 'DocScanner 16 May 2025 6-46 pm.pdf',
 'Domain.docx',
 'Environment Setup.docx',
 'EXCEL ASSIGNMENT  21 TO 25..xlsx',
 'FINAL.docx',
 'FINAL.pdf',
 'Fwd_ attendance report june 2025 - nayna@italentindia.com - iTalent India Management Consultants (P) Ltd. Mail.html',
 'Fwd_ attendance report june 2025 - nayna@italentindia.com - iTalent India Management Consultants (P) Ltd. Mail_files',
 'German Institution  list.xlsx',
 'German Lanunage Intitution list.xlsx',
 'GME.pdf',
 'heart-disease.csv',
 'heartt-disease.csv',
 'Hierarchy.docx',
 'Hiring sheet -2025.xlsx',
 'ilovepdf_merged.pdf',
 'IMG_20250828_170852_1.jpg',
 'internship repo.pdf',
 'Introduction.docx',
 'Kartik Chimurkar CV(1) (1).docx',
 'Kartik Chimurkar CV(1).docx',
 'Kartik Chimurkar CV.docx',
 'Kartik Chimurkar CV.pdf',
 'Kartik Chimurkar_CV (1) (1).pdf',
 'Kartik Chimurkar_CV (1) (2).pdf',
 'Kartik Chimurkar_CV (1).docx',
 'Kartik Chimurkar_CV (1).pdf',
 'Kartik_Chimurkar_CV.docx',
 'Kartik_Chimurkar_CV.pdf',
 'Kartik_Chimurkar_CV_ (1).docx',
 'Kartik_Chimurkar_CV_ (1).pdf',
 'Kartik_Chimurkar_CV_ (2).docx',
 'Kartik_Chimurkar_CV_.docx',
 'Kartik_Chimurkar_CV_.pdf',
 'KPI.docx',
 'KRA.docx',
 'Ktu certificate .pdf',
 'Left_Thumb.jpg',
 'major project final ppt ..pptx',
 'MINTREE CTC SHEET.xlsx',
 'mongodb-compass-1.48.2-darwin-x64.dmg',
 'mongodb-compass-1.48.2-win32-x64.msi',
 'MSTeamsSetup.exe',
 'mysql-installer-web-community-8.0.44.0 (1).msi',
 'mysql-installer-web-community-8.0.44.0 (2).msi',
 'mysql-installer-web-community-8.0.44.0 (3).msi',
 'mysql-installer-web-community-8.0.44.0.msi',
 'Naukri Launcher Installer.exe',
 'nayn photo (1).jpg',
 'nayn photo.jpg',
 'nayna aadhar card.jpg',
 'NAYNA CV (1).docx',
 'NAYNA CV (2).docx',
 'NAYNA CV (3).docx',
 'NAYNA CV (4).docx',
 'NAYNA CV (5).docx',
 'NAYNA CV (6).docx',
 'NAYNA CV (7).docx',
 'NAYNA CV (8).docx',
 'NAYNA CV (9).docx',
 'NAYNA CV.docx',
 'Nayna CV.pdf',
 'Nayna Cv1.docx',
 'Nayna Laxane CV (1).pdf',
 'Nayna Laxane CV (2).pdf',
 'Nayna Laxane CV (3).pdf',
 'Nayna Laxane CV (4) (1).pdf',
 'Nayna Laxane CV (4).pdf',
 'Nayna Laxane CV (5).pdf',
 'Nayna Laxane CV (6).docx',
 'Nayna Laxane CV (6).pdf',
 'Nayna Laxane CV (7).pdf',
 'Nayna Laxane CV (8).pdf',
 'Nayna Laxane CV (9) (1).docx',
 'Nayna Laxane CV (9) (2).docx',
 'Nayna Laxane CV (9).docx',
 'Nayna Laxane CV (9).pdf',
 'Nayna Laxane CV.docx',
 'Nayna Laxane CV.pdf',
 'Nayna Laxane Resume (1).pdf',
 'Nayna Laxane Resume (2) (1).docx',
 'Nayna Laxane Resume (2).docx',
 'Nayna Laxane Resume (2).pdf',
 'Nayna Laxane Resume.docx',
 'Nayna Laxane Resume.pdf',
 'NAYNA LAXANE_CV 1.pdf',
 'NAYNA LAXANE_CV.docx',
 'NAYNA LAXANE_CV.pdf',
 'NAYNA LAXANE_FINANCE.docx',
 'NAYNA LAXANE_FINANCE.pdf',
 'NAYNA LAXANE_RESUME. (2).pdf',
 'NAYNA LAXANE_RESUME..pdf',
 'nayna licese (1) - Copy.jpg',
 'nayna licese (1).jpg',
 'nayna licese.jpg',
 'nayna sign new (1).jpg',
 'nayna sign new.jpg',
 'nayna sign.jpg',
 'NAYNA _LAXANE_HR.docx',
 'NAYNA _LAXANE_HUMAN RESOURCE.pdf',
 'Nayna. Resume (1).pdf',
 'Nayna. Resume (2).pdf',
 'Nayna. Resume (3).pdf',
 'Nayna. Resume.pdf',
 'NISM Admit Card KARTIK.pdf',
 'NISM Admit Card NAYNA.pdf',
 'node-v24.12.0-x64.msi',
 'OKR.docx',
 'one-skill-you-should-focus-on (1).xlsx',
 'one-skill-you-should-focus-on (2).xlsx',
 'one-skill-you-should-focus-on.xlsx',
 'OperaSetup.exe',
 'P.P.PG.pdf',
 'Pan tanu.pdf',
 'Pan tanu_compressed.pdf',
 'Pan.jpeg',
 'Pancard.jpg',
 'PARAG SINHA June-2025.pdf',
 'Part 3 (2).zip',
 'Passport Feburary 2025.pdf',
 'Payment receipt IBPS.pdf',
 'photo (2).jpg',
 'Photo.jpeg',
 'photo.jpg',
 'Photograph (1).jpg',
 'Photograph (2).jpg',
 'Photograph.jpg',
 'Play Store Data (1).csv',
 'Play Store Data (2).csv',
 'Play Store Data (3).csv',
 'Play Store Data.csv',
 'Play Store Data.xlsx',
 'Prerna Laxane Cv.pdf',
 'PRERNA LAXANE RESUME.pdf',
 'PRERNA LAXANE_RESUME[1] (1).docx',
 'PRERNA LAXANE_RESUME[1] (2).docx',
 'PRERNA LAXANE_RESUME[1] (3).docx',
 'PRERNA LAXANE_RESUME[1] (4) (1).pdf',
 'PRERNA LAXANE_RESUME[1] (4).docx',
 'PRERNA LAXANE_RESUME[1] (4).pdf',
 'PRERNA LAXANE_RESUME[1].docx',
 'PRERNA LAXANE_RESUME[1].pdf',
 'prerna.code-workspace',
 'Prerna_Laxane RESUME.docx',
 'Prerna_Laxane RESUME.pdf',
 'Prerna_Laxane_RESUME.pdf',
 'PRERNA_REAL_INTERVIEW_HANDBOOK_DETAILED_PART_A.pdf',
 'PROJECT (5)_merged (1).docx',
 'PROJECT (5)_merged (1).pdf',
 'python-3.13.2-amd64 (1).exe',
 'python-3.13.2-amd64 (2).exe',
 'python-3.13.2-amd64.exe',
 'python-manager-25.2 (1).msix',
 'python-manager-25.2.msix',
 'Responsibilities.docx',
 'Rohit Europass CV.pdf',
 'Sarang Tadakhe CV..pdf',
 'Sarang Tadakhe CV.docx',
 'Sarang Tadakhe CV.pdf',
 'SCORE CARD.pdf',
 'Shreyas Gurav Resume.pdf',
 'Shreyas Vadgave Resume.pdf',
 'Shreyash Ravindra Gurav CV (1).pdf',
 'Shreyash Ravindra Gurav CV.pdf',
 'SHUBHAM VAIDYA_June-2025.pdf',
 'Sign.jpg',
 'Signature.jpg',
 'SIH2025-DD 19-sep[1]  - (1).pptx',
 'sonali M.pdf',
 'sonali.thesis.pdf',
 'Staff Attendance Report (July).pdf',
 'Swati.jpg',
 'Swati.pdf',
 'synopsis .synopsis (1).docx',
 'synopsis .synopsis.docx',
 'Synopsis Format (1).docx',
 'Synopsis Format.docx',
 'Synopsis Format.pdf',
 'Synopsis Front page.docx',
 'Synopsis Front page.pdf',
 'Synopsis index.docx',
 'Synopsis_SustainabilityScorePredictor2 (3).docx',
 'Synopsis_SustainabilityScorePredictor2 (3).pdf',
 'takeout-20250520T051730Z-001.zip',
 'takeout-20250520T051730Z-1-001.zip',
 'Tanaya Agre (Resume).pdf',
 'Teams.docx',
 'Technical SPRINT (1).pdf',
 'Technical SPRINT (2).pdf',
 'Technical SPRINT.pdf',
 'Techstack.docx',
 'Telegram Desktop',
 'Thesis major project.docx',
 'Timeline.docx',
 'Tools.docx',
 'tsetup-x64.4.14.3.exe',
 'User Reviews (1).csv',
 'User Reviews.csv',
 'Viraj Nitin Kank-CV.pdf',
 'VisualStudioSetup (1).exe',
 'VisualStudioSetup.exe',
 'VSCodeUserSetup-arm64-1.97.1.exe',
 'VSCodeUserSetup-x64-1.97.1 (1).exe',
 'VSCodeUserSetup-x64-1.97.1 (2).exe',
 'VSCodeUserSetup-x64-1.97.1 (3).exe',
 'VSCodeUserSetup-x64-1.97.1.exe',
 'Webinar_intersted_candidates__(2.xlsx',
 'WhatsApp Image 2023-12-13 at 23.34.17_231c7296.jpg',
 'WhatsApp Image 2023-12-13 at 23.34.17_e32551e3.jpg',
 'WhatsApp Image 2023-12-13 at 23.34.17_f10387e8.jpg',
 'WhatsApp Image 2023-12-13 at 23.34.17_fde505d8.jpg',
 'WhatsApp Image 2025-09-20 at 17.09.57_58f1fafc.png',
 'WhatsApp Image 2025-11-03 at 20.41.16_e3afb62e.jpg',
 'WhatsApp Image 2025-11-03 at 20.42.19_e682bd55.jpg',
 'wps_lid.lid-i9oJfEqZb6OB (1).exe',
 'wps_lid.lid-i9oJfEqZb6OB.exe']

In [29]:
import os
os.listdir(r"C:\Users\NAYNALAXANE\Desktop\internship")

['Analysis.ipynb',
 'Analysis2_files',
 'Analysis3_files',
 'Analysis_files',
 'Global EV Data 2024_files',
 'heart-disease.csv',
 'heart-disease_files',
 'INTERNSHIP REPO 1.docx',
 'internship repo.docx',
 'play store data.csv',
 'play store data.csv.csv',
 'README_files',
 'Untitled_files',
 'User Reviews (1).csv']

In [30]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [31]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'], format='mixed', errors='coerce')

In [32]:
df['Last Updated'].head()

0   2018-01-07
1   2018-01-15
2   2018-08-01
3   2018-06-08
4   2018-06-20
Name: Last Updated, dtype: datetime64[ns]

In [33]:
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

task3_df = df[
    (df['Reviews'] > 500) &
    (~df['App'].str.startswith(('X','Y','Z'), na=False)) &
    (~df['App'].str.contains('S', case=False, na=False)) &
    (df['Category'].str.startswith(('E','C','B'), na=False))
]

In [34]:
task3_df[['App','Category','Reviews']].head()

                                    App             Category   Reviews
107                         Ulta Beauty               BEAUTY   42050.0
136                      Rainbow Camera               BEAUTY    3871.0
140    E-Book Read - Read Book for free  BOOKS_AND_REFERENCE    1857.0
141  Download free book with green book  BOOKS_AND_REFERENCE    4478.0
142                           Wikipedia  BOOKS_AND_REFERENCE  577550.0

In [35]:
task3_df['Category'] = task3_df['Category'].replace({
    'BEAUTY':'सौंदर्य',
    'BUSINESS':'வணிகம்',
    'DATING':'Partnersuche'
})

task3_df['Month'] = task3_df['Last Updated'].dt.to_period('M').astype(str)

C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\4204777190.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task3_df['Category'] = task3_df['Category'].replace({
C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\4204777190.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task3_df['Month'] = task3_df['Last Updated'].dt.to_period('M').astype(str)

In [36]:
trend_df = task3_df.groupby(['Month','Category']) ['Installs'].sum().reset_index()

In [37]:
task3_df[['Category','Month']].head()

                Category    Month
107              सौंदर्य  2018-06
136              सौंदर्य  2018-07
140  BOOKS_AND_REFERENCE  2018-08
141  BOOKS_AND_REFERENCE  2017-07
142  BOOKS_AND_REFERENCE  2018-08

In [38]:
df['Installs'] = df['Installs'].astype(str).str.replace('+','').str.replace(',','')
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

trend_df = task3_df.groupby(['Month','Category'])['Installs'].sum().reset_index()

In [39]:
trend_df.head()

     Month       Category    Installs
0  2014-01  COMMUNICATION    100000.0
1  2014-03  COMMUNICATION    100000.0
2  2014-05         வணிகம்    100000.0
3  2014-07  COMMUNICATION  10000000.0
4  2014-07      EDUCATION     10000.0

In [40]:
trend_df = trend_df.sort_values(['Category','Month'])

trend_df['Growth'] = trend_df.groupby('Category')['Installs'].pct_change()

trend_df.head()

      Month             Category    Installs    Growth
5   2014-10  BOOKS_AND_REFERENCE    500000.0       NaN
6   2014-11  BOOKS_AND_REFERENCE   5000000.0  9.000000
10  2015-07  BOOKS_AND_REFERENCE  10000000.0  1.000000
18  2016-06  BOOKS_AND_REFERENCE     60000.0 -0.994000
21  2016-08  BOOKS_AND_REFERENCE    100000.0  0.666667

In [41]:
from datetime import datetime
import plotly.express as px
import plotly.io as pio

pio.renderers.default = 'browser'

current_hour = datetime.now().hour

if 18 <= current_hour < 21:

    fig = px.line(
        trend_df,
        x='Month',
        y='Installs',
        color='Category',
        title='Total Installs Trend by Category'
    )

    growth_df = trend_df[trend_df['Growth'] > 0.20]

    for cat in growth_df['Category'].unique():
        temp = growth_df[growth_df['Category'] == cat]

        fig.add_scatter(
            x=temp['Month'],
            y=temp['Installs'],
            fill='tozeroy',
            mode='none',
            name=f'Growth >20% {cat}'
        )

    fig.show()

else:
    print("Graph available only between 6 PM and 9 PM IST")

Graph available only between 6 PM and 9 PM IST

## TASK 4

In [42]:
import pandas as pd

In [43]:
df = pd.read_csv(r"C:\Users\NAYNALAXANE\Downloads\play store data.csv")

In [44]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [45]:
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')
df['Sizw'] = df['Size'].astype(str).str.replace('M','')
df['Size'] = df['Size'].replace('Varies with device', None)
df['Size'] = pd.to_numeric(df['Size'], errors='coerce')
df['Last Updated'] = pd.to_datetime(df['Last Updated'], format='mixed', errors='coerce')

In [46]:
df[['Reviews','Size','Last Updated']].head()

    Reviews  Size Last Updated
0     159.0   NaN   2018-01-07
1     967.0   NaN   2018-01-15
2   87510.0   NaN   2018-08-01
3  215644.0   NaN   2018-06-08
4     967.0   NaN   2018-06-20

In [47]:
df['Size'] =df['Size'].astype(str)
df['Size'] = df['Size'].str.replace('M','',regex=False)
df['Size'] = df['Size'].str.replace('k','',regex=False)
df['Size'] = df['Size'].replace('varies with device', None)
df['Size'] = pd.to_numeric(df['Size'], errors='coerce')

In [48]:
df['Size'].head(10)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: Size, dtype: float64

In [49]:
df['Size'].astype(str).head(10)

0    nan
1    nan
2    nan
3    nan
4    nan
5    nan
6    nan
7    nan
8    nan
9    nan
Name: Size, dtype: object

In [50]:
df = pd.read_csv(
r"C:\Users\NAYNALAXANE\Downloads\Play Store Data (1).csv"
)

In [51]:
import pandas as pd

df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

df['Size'] = df['Size'].astype(str)
df['Size'] = df['Size'].str.replace('M','', regex=False)

df['Size'] = df['Size'].apply(
    lambda x: str(float(x.replace('k',''))/1024)
    if 'k' in x else x
)

df['Size'] = df['Size'].replace(
    'Varies with device',
    None
)

df['Size'] = pd.to_numeric(
    df['Size'],
    errors='coerce'
)

df['Last Updated'] = pd.to_datetime(
    df['Last Updated'],
    format='mixed',
    errors='coerce'
)

In [52]:
df[['Size']].head(10)

   Size
0  19.0
1  14.0
2   8.7
3  25.0
4   2.8
5   5.6
6  19.0
7  29.0
8  33.0
9   3.1

In [53]:
task4_df = df[
    (df['Rating'] >= 4.2) &
    (df['Reviews'] >= 1000) &
    (df['Size'] >= 20) &
    (df['Size'] <= 80) &
    (df['Category'].str.startswith(('T','P'), na=False)) &
    (~df['App'].str.contains(r'\d', regex=True, na=False))
]

In [54]:
task4_df[['App','Category','Rating','Reviews','Size']].head()

,App,Category,Rating,Reviews,Size
2802,"Shutterfly: Free Prints, Photo Books, Cards, G...",PHOTOGRAPHY,4.6,98716.0,59.0
2803,FreePrints – Free Photos Delivered,PHOTOGRAPHY,4.8,109500.0,37.0
2811,"Face Filter, Selfie Editor - Sweet Camera",PHOTOGRAPHY,4.7,142634.0,22.0
2822,Makeup Editor -Beauty Photo Editor & Selfie Ca...,PHOTOGRAPHY,4.5,3378.0,30.0
2823,Makeup Photo Editor: Makeup Camera & Makeup Ed...,PHOTOGRAPHY,4.4,10525.0,25.0

In [55]:
task4_df['Last Updated'] = pd.to_datetime(
    task4_df['Last Updated'],
    errors='coerce'
)

task4_df['Month'] = (
    task4_df['Last Updated']
    .dt.to_period('M')
    .astype(str)
)

task4_df['Category'] = task4_df['Category'].replace({
    'TRAVEL_AND_LOCAL':'Voyage et Local',
    'PRODUCTIVITY':'Productividad',
    'PHOTOGRAPHY':'写真'
})

C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3602250254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task4_df['Last Updated'] = pd.to_datetime(
C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3602250254.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task4_df['Month'] = (
C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3602250254.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task4_df['Category'] = task4_df['Category'].replace({

In [56]:
task4_df[['Category','Month']].head()

     Category    Month
2802       写真  2018-08
2803       写真  2018-08
2811       写真  2018-07
2822       写真  2018-07
2823       写真  2018-07

In [57]:
task4_df['Installs'] = task4_df['Installs'].astype(str)
task4_df['Installs'] = task4_df['Installs'].str.replace('+','', regex=False)
task4_df['Installs'] = task4_df['Installs'].str.replace(',','', regex=False)
task4_df['Installs'] = pd.to_numeric(task4_df['Installs'], errors='coerce')

area_df = task4_df.groupby(
    ['Month','Category']
)['Installs'].sum().reset_index()

area_df = area_df.sort_values(
    ['Category','Month']
)

area_df['Cumulative_Installs'] = area_df.groupby(
    'Category'
)['Installs'].transform('cumsum')

area_df['Growth'] = area_df.groupby(
    'Category'
)['Installs'].pct_change()

C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3878121220.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task4_df['Installs'] = task4_df['Installs'].astype(str)
C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3878121220.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task4_df['Installs'] = task4_df['Installs'].str.replace('+','', regex=False)
C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3878121220.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task4_df['Installs'] = task4_df['Installs'].str.replace(',','', regex=False)
C:\Users\NAYNALAXANE\AppData\Local\Temp\ipykernel_1048\3878121220.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  task4_df['Installs'] = pd.to_numeric(task4_df['Installs'], errors='coerce')

In [58]:
area_df.head()

      Month         Category  Installs  Cumulative_Installs  Growth
16  2018-03        PARENTING    100000               100000     NaN
19  2018-05        PARENTING  10000000             10100000   99.00
26  2018-07        PARENTING    600000             10700000   -0.94
2   2016-12  PERSONALIZATION   2000000              2000000     NaN
7   2017-09  PERSONALIZATION   1000000              3000000   -0.50

In [59]:
from datetime import datetime
import pytz
import plotly.express as px

ist = pytz.timezone('Asia/Kolkata')
current_time = datetime.now(ist)

if 16 <= current_time.hour < 18:

    fig = px.area(
        area_df,
        x='Month',
        y='Cumulative_Installs',
        color='Category',
        title='Cumulative Installs by Category'
    )

    growth_df = area_df[area_df['Growth'] > 0.25]

    for cat in growth_df['Category'].unique():
        temp = growth_df[growth_df['Category'] == cat]

        fig.add_scatter(
            x=temp['Month'],
            y=temp['Cumulative_Installs'],
            fill='tozeroy',
            mode='none',
            name=f'Growth >25% {cat}'
        )

    fig.show()

else:
    print("Chart available only between 4 PM and 6 PM IST")

Chart available only between 4 PM and 6 PM IST

In [60]:
import plotly.io as pio
pio.renderers.default = 'browser'

## TASK 5

In [61]:
import pandas as pd

In [62]:
df = pd.read_csv(r"C:\Users\NAYNALAXANE\Downloads\play store data.csv")

In [63]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [64]:
import pandas as pd

df['Rating'] = pd.to_numeric(
    df['Rating'],
    errors='coerce'
)

df['Reviews'] = pd.to_numeric(
    df['Reviews'],
    errors='coerce'
)

df['Size'] = df['Size'].astype(str)
df['Size'] = df['Size'].str.replace('M','', regex=False)

df['Size'] = df['Size'].apply(
    lambda x: str(float(x.replace('k',''))/1024)
    if 'k' in x else x
)

df['Size'] = df['Size'].replace(
    'Varies with device',
    None
)

df['Size'] = pd.to_numeric(
    df['Size'],
    errors='coerce'
)

df['Installs'] = df['Installs'].astype(str)
df['Installs'] = df['Installs'].str.replace('+','', regex=False)
df['Installs'] = df['Installs'].str.replace(',','', regex=False)
df['Installs'] = pd.to_numeric(
    df['Installs'],
    errors='coerce'
)

df['Last Updated'] = pd.to_datetime(
    df['Last Updated'],
    format='mixed',
    errors='coerce'
)

In [65]:
df[['Rating','Size','Installs','Last Updated']].head()

   Rating  Size    Installs Last Updated
0     4.1  19.0     10000.0   2018-01-07
1     3.9  14.0    500000.0   2018-01-15
2     4.7   8.7   5000000.0   2018-08-01
3     4.5  25.0  50000000.0   2018-06-08
4     4.3   2.8    100000.0   2018-06-20

In [66]:
task5_df = df[
    (df['Rating'] > 4.0) &
    (df['Size'] >= 10) &
    (df['Last Updated'].dt.month == 1)
]

In [67]:
task5_df[['App','Category','Rating','Size','Installs','Last Updated']].head()

,App,Category,Rating,Size,Installs,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19.0,10000.0,2018-01-07
33,Easy Origami Ideas,ART_AND_DESIGN,4.2,11.0,100000.0,2018-01-06
44,Popsicle Sticks and Similar DIY Craft Ideas,ART_AND_DESIGN,4.2,12.0,10000.0,2018-01-03
446,Video Caller Id,COMMUNICATION,4.2,17.0,1000000.0,2018-01-24
719,Monster Truck Driver & Racing,EDUCATION,4.4,51.0,1000000.0,2017-01-19

In [68]:
top10_cat = (
    task5_df.groupby('Category')
    .agg({
        'Installs':'sum',
        'Rating':'mean',
        'Reviews':'sum'
    })
    .sort_values('Installs', ascending=False)
    .head(10)
    .reset_index()
)

top10_cat.head(10)

           Category     Installs    Rating    Reviews
0            FAMILY  177394820.0  4.414286  4524786.0
1            SPORTS  120511000.0  4.342857  1982017.0
2              GAME  103691000.0  4.348148  2157275.0
3     ENTERTAINMENT   51000000.0  4.250000  1238948.0
4   PERSONALIZATION   15060000.0  4.475000   155996.0
5       PHOTOGRAPHY   10000000.0  4.300000   542561.0
6         EDUCATION    2000000.0  4.400000    57645.0
7          SHOPPING    2000000.0  4.200000    19950.0
8             TOOLS    1010000.0  4.200000     8010.0
9  TRAVEL_AND_LOCAL    1001000.0  4.100000      974.0

In [69]:
import plotly.io as pio
pio.renderers.default = 'browser'

In [70]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

if 15 <= current_time.hour < 17:

    fig = make_subplots(specs=[[{"secondary_y": True}]])

    fig.add_trace(
        go.Bar(
            x=top10_cat['Category'],
            y=top10_cat['Rating'],
            name='Average Rating'
        ),
        secondary_y=False
        
    )

    fig.add_trace(
        go.Bar(
            x=top10_cat['Category'],
            y=top10_cat['Reviews'],
            name='Total Reviews'
        ),
        secondary_y=True
    )

    fig.update_layout(
        title='Average Rating and Total Reviews by Top 10 Categories',
        barmode='group'
    )
    fig.update_yaxes(title_text='Rating', secondary_y=False)
    fig.update_yaxes(title_text='Reviews', secondary_y=True)
    fig.show()

else:
    print("Chart available only between 3 PM and 5 PM IST")

Chart available only between 3 PM and 5 PM IST

In [71]:
top10_cat = top10_cat[top10_cat['Rating'] >= 4.0]

## TASK 6

In [72]:
import pandas as pd

In [73]:
df = pd.read_csv(r"C:\Users\NAYNALAXANE\Downloads\play store data.csv")

In [74]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [75]:
df[['Price','Android Ver']].head()

  Price   Android Ver
0     0  4.0.3 and up
1     0  4.0.3 and up
2     0  4.0.3 and up
3     0    4.2 and up
4     0    4.4 and up

In [76]:
df['Price'] = df['Price'].astype(str)
df['Price'] = df['Price'].str.replace('$','', regex=False)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Android Ver'] = df['Android Ver'].astype(str)
df['Android num'] = df['Android Ver'].str.extract(r'(\d+\.?\d*)')
df['Android_num'] = pd.to_numeric(df['Android num'], errors='coerce')

In [77]:
df[['Price','Android Ver','Android_num']].head()

   Price   Android Ver  Android_num
0    0.0  4.0.3 and up          4.0
1    0.0  4.0.3 and up          4.0
2    0.0  4.0.3 and up          4.0
3    0.0    4.2 and up          4.2
4    0.0    4.4 and up          4.4

In [78]:
df['Installs'] = df['Installs'].astype(str)
df['Installs'] = df['Installs'].str.replace('+','', regex=False)
df['Installs'] = df['Installs'].str.replace(',','', regex=False)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

In [79]:
df['Revenue'] = df['Price'] * df['Installs']

In [80]:
df[['Price','Installs','Revenue']].head()

   Price    Installs  Revenue
0    0.0     10000.0      0.0
1    0.0    500000.0      0.0
2    0.0   5000000.0      0.0
3    0.0  50000000.0      0.0
4    0.0    100000.0      0.0

In [81]:
df['App_length'] = df['App'].astype(str).str.len()

In [82]:
df[['App','App_length','Content Rating','Size','Android_num','Revenue']].head()

,App,App_length,Content Rating,Size,Android_num,Revenue
0,Photo Editor & Candy Camera & Grid & ScrapBook,46,Everyone,19M,4.0,0.0
1,Coloring book moana,19,Everyone,14M,4.0,0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",50,Everyone,8.7M,4.0,0.0
3,Sketch - Draw & Paint,21,Teen,25M,4.2,0.0
4,Pixel Draw - Number Art Coloring Book,37,Everyone,2.8M,4.4,0.0

In [83]:
df['Size'] = df['Size'].astype(str)
df['Size'] = df['Size'].str.replace('M','', regex=False)
df['Size'] = pd.to_numeric(df['Size'], errors='coerce')

In [84]:
df[['Size']].head()

   Size
0  19.0
1  14.0
2   8.7
3  25.0
4   2.8

In [85]:
task6_df = df[
    (df['Installs'] >= 10000) &
    (df['Revenue'] > 10000) &
    (df['Android_num'] >= 4.0) &
    (df['Size'] > 15) &
    (df['Content Rating'] == 'Everyone') &
    (df['App_length'] <= 30)
]

In [86]:
task6_df[['App','Category','Type','Installs','Revenue']].head()

                      App            Category  Type  Installs    Revenue
853       Toca Life: City           EDUCATION  Paid  500000.0  1995000.0
854   Toca Life: Hospital           EDUCATION  Paid  100000.0   399000.0
1335    Meditation Studio  HEALTH_AND_FITNESS  Paid   10000.0    39900.0
1831     The Game of Life                GAME  Paid  100000.0   299000.0
1833   The Room: Old Sins                GAME  Paid  100000.0   499000.0

In [87]:
top3_cat = (
    task6_df.groupby('Category')['Installs']
    .sum()
    .sort_values(ascending=False)
    .head(3)
    .index
)

top3_task6 = task6_df[
    task6_df['Category'].isin(top3_cat)
]

In [88]:
top3_task6[['Category','Type','Installs','Revenue']].head(10)

             Category  Type   Installs    Revenue
2151           FAMILY  Paid   500000.0  1995000.0
2191           FAMILY  Paid    10000.0    39900.0
2204           FAMILY  Paid    10000.0    39900.0
2883      PHOTOGRAPHY  Paid  1000000.0  5990000.0
2912      PHOTOGRAPHY  Paid  1000000.0  5990000.0
2950      PHOTOGRAPHY  Paid  1000000.0  5990000.0
3405  PERSONALIZATION  Paid  1000000.0   990000.0
4260           FAMILY  Paid  1000000.0   990000.0
4429           FAMILY  Paid    10000.0    24900.0
5412           FAMILY  Paid   100000.0   299000.0

In [89]:
from datetime import datetime
import pytz
from plotly.subplots import make_subplots
import plotly.graph_objects as go

ist = pytz.timezone('Asia/Kolkata')
current_time = datetime.now(ist)

if 13 <= current_time.hour < 14:

    chart_data = (
        top3_task6.groupby(['Category','Type'])
        .agg({
            'Installs':'mean',
            'Revenue':'mean'
        })
        .reset_index()
    )

    fig = make_subplots(specs=[[{"secondary_y": True}]])

    fig.add_trace(
        go.Bar(
            x=chart_data['Category'] + ' - ' + chart_data['Type'],
            y=chart_data['Installs'],
            name='Average Installs'
        ),
        secondary_y=False
    )

    fig.add_trace(
        go.Scatter(
            x=chart_data['Category'] + ' - ' + chart_data['Type'],
            y=chart_data['Revenue'],
            name='Revenue',
            mode='lines+markers'
        ),
        secondary_y=True
    )

    fig.update_layout(
        title='Average Installs and Revenue for Free vs Paid Apps (Top 3 Categories)'
    )

    fig.update_yaxes(title_text='Average Installs', secondary_y=False)
    fig.update_yaxes(title_text='Revenue', secondary_y=True)

    fig.show()

else:
    print("Chart available only between 1 PM and 2 PM IST")

Chart available only between 1 PM and 2 PM IST